// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreatePollResponse struct {
	ID    *string `json:"id,omitempty"`
	Error *string `json:"error,omitempty"`
}

type Option struct {
	Name  string `json:"name"`
	Votes int    `json:"votes"`
}

type OptionsInput struct {
	Names []string `json:"names"`
}

type VoteInput struct {
	ID     string  `json:"id"`
	Option *string `json:"option,omitempty"`
}

type VoteResponse struct {
	Message string `json:"message"`
}
